name: Release (Build & Publish)

on:
  workflow_dispatch:
  release:
    types: [ published ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: build
    uses: ovunccetin/hamlette/.github/workflows/build.yml@main
    with:
      ref: ${{ github.event.release.tag_name || github.ref }}
      python-version: '3.12'
      verify-version: false
