name: Release (Build & Publish)

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'The git ref to checkout (branch, tag, SHA). Defaults to the release tag or the default branch.'
        required: false
        type: string

      verify-version:
        description: 'Verify that the package version matches the release tag.'
        required: false
        type: boolean

      python-version:
        description: 'The Python version to set up. Defaults to 3.12.'
        required: false
        type: string

  release:
    types: [ published ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref || github.event.release.tag_name }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ github.event.inputs.python-version || '3.12' }}
          cache: pip

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pipx install poetry

      - name: Install dependencies (no root)
        run: |
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-ansi --no-root --without dev

      - name: Verify version against release tag
        if: ${{ github.event.inputs.verify-version == 'true' }}
        run: |
          RELEASE_VERSION=${{ github.event.inputs.ref || github.event.release.tag_name }}
          RELEASE_VERSION=${RELEASE_VERSION#v}

          PACKAGE_VERSION=$(poetry version -s)
          if [ "$RELEASE_VERSION" != "$PACKAGE_VERSION" ]; then
            echo "Version mismatch: Release version is '$RELEASE_VERSION' but package version is '$PACKAGE_VERSION'"
            exit 1
          fi

      - name: Build packages (sdist and wheel)
        run: |
          poetry build --no-interaction --no-ansi

      - name: Upload dist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*

  publish:
    name: Publish to PyPI or TestPyPI
    needs: build
    runs-on: ubuntu-latest
    env:
      POETRY_PYPI_TOKEN_PYPI: ${{ secrets.POETRY_PYPI_TOKEN_PYPI }}
      POETRY_PYPI_TOKEN_TESTPYPI: ${{ secrets.POETRY_PYPI_TOKEN_TESTPYPI }}
    steps:
      - name: Download dist artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pipx install poetry

      - name: Publish to PyPI or TestPyPI
        run: |
          if [[ "${{ github.event.inputs.ref || github.event.release.tag_name }}" =~ (pre|rc|dev|test) ]]; then
            echo "Publishing to TestPyPI..."
            poetry publish -r testpypi -u __token__ -p $POETRY_PYPI_TOKEN_TESTPYPI --no-interaction --no-ansi dist/*
          else
            echo "Publishing to PyPI..."
            poetry publish -u __token__ -p $POETRY_PYPI_TOKEN_PYPI --no-interaction --no-ansi dist/*
          fi