name: Release (Build & Publish)

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'The git ref to checkout (branch, tag, SHA). Defaults to the release tag or the default branch.'
        required: false
        type: string

      verify-version:
        description: 'Verify that the package version matches the release tag.'
        required: false
        type: boolean

      python-version:
        description: 'The Python version to set up. Defaults to 3.12.'
        required: false
        type: string

  release:
    types: [ published ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: build
    uses: ovunccetin/hamlette/.github/workflows/build.yml@main
    with:
      ref: ${{ github.event.inputs.ref || github.event.release.tag_name || github.ref }}
      python-version: ${{ github.event.inputs.python-version || '3.12' }}
      verify-version: ${{ github.event.inputs.verify-version || true }}
